ci: includes fail-fast: false in the matrix strategy, so all jobs will run to completion even if one fails

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -10,6 +10,7 @@ jobs:
   examples-building-and-testing:
     runs-on: ${{ matrix.os }}
     strategy:
+      fail-fast: false # Continue other jobs if one fails
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
         folder:
@@ -25,8 +26,7 @@ jobs:
       - name: Set up V
         uses: vlang/setup-v@v1.4
       - name: Remove Vlang folder to avoid conflicts
-        run: |
-          rm -rf -v ./vlang || true
+        run: rm -rf -v ./vlang || true
       - name: Install dependencies
         shell: bash
         run: |
